//
//  MyReminderStyleKit.h
//  MyReminders
//
//  Created by jnagel on 5/1/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyReminderStyleKit : NSObject

// Drawing Methods
+ (void)drawRedGradientBarWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfRedGradientBarWithFrame: (CGRect)frame;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
